/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        transparent: "transparent",
        current: "currentColor",
        white: "#ffffff",
        black: "#000000",
        gray: {
          lighter: "#D4D4D4",
          light: "#F2F2F2",
          DEFAULT: "#6B7280",
          deep: "#374151",
        },
        overlay: "rgba(0,0,0, 0.3)",
        "overlay-hard": "rgba(0,0,0, 0.85)",
        active: "#CDFFCD",
        "active-deep": "#007F00",
        inactive: "#FFECCC",
        "inactive-deep": "#965E00",
      },
      fontFamily: {
        header: [
          "Inconsolata",
          " system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "Noto Sans",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
        text: [
          "Inter",
          " system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "Noto Sans",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
      },
      gridTemplateColumns: {
        // gallery image list
        "cards-list": "repeat(auto-fit, minmax(300px, 1fr))",
      },
    },
  },
  plugins: [],
};
