import type { NextPage } from "next";
import Head from "next/head";

// components
import Header from "@/src/components/header";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Good Doctor App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4"></main>
    </>
  );
};

export default Home;

